CREATE TABLE ORDERS (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER REFERENCES USERS(ID) ON DELETE CASCADE,
    STATUS VARCHAR(20) CHECK (STATUS IN ('active', 'complete')) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);