CREATE TABLE ORDER_PRODUCTS (
    ID SERIAL PRIMARY KEY,
    ORDER_ID INTEGER REFERENCES ORDERS(ID) ON DELETE CASCADE,
    PRODUCT_ID INTEGER REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    QUANTITY INTEGER NOT NULL CHECK (QUANTITY > 0)
);